<?php

declare(strict_types=1);

use App\Controllers\Admin\AdminController;
use App\Controllers\User\DashboardController;
use App\Controllers\User\PayController;
use App\Controllers\User\ProfileController;
use App\Controllers\User\ReservationController;
use App\Controllers\User\StudioController;
use App\Controllers\Web\AuthController;
use App\Controllers\Web\PublicController;
use App\Controllers\Web\StripeWebhookController;
use App\Middleware\AdminMiddleware;
use App\Middleware\AuthMiddleware;
use App\Middleware\GuestMiddleware;

$router = app()->router();

$router->get('/', [PublicController::class, 'home']);
$router->get('/404', static function (): never {
    app()->abort(404);
});
$router->get('/cenik', [PublicController::class, 'pricing']);
$router->get('/faq', [PublicController::class, 'faq']);
$router->get('/kontakt', [PublicController::class, 'contact']);
$router->post('/kontakt', [PublicController::class, 'sendContact']);
$router->get('/zajem', [PublicController::class, 'interest']);
$router->post('/zajem', [PublicController::class, 'signupInterest']);
$router->get('/dokument/{slug}', [PublicController::class, 'legal']);
$router->get('/manifest.json', [PublicController::class, 'manifest']);
$router->get('/avatar/{id}', [PublicController::class, 'avatar']);
$router->get('/uploads/avatars/{file}', [PublicController::class, 'uploadedAvatar']);

$router->get('/registrace', [AuthController::class, 'showRegister'], [GuestMiddleware::class]);
$router->post('/registrace', [AuthController::class, 'register'], [GuestMiddleware::class]);
$router->get('/prihlaseni', [AuthController::class, 'showLogin'], [GuestMiddleware::class]);
$router->get('/prihlaseni/google', [AuthController::class, 'googleStart'], [GuestMiddleware::class]);
$router->get('/prihlaseni/google/callback', [AuthController::class, 'googleCallback'], [GuestMiddleware::class]);
$router->get('/prihlaseni/apple', [AuthController::class, 'appleStart'], [GuestMiddleware::class]);
$router->post('/prihlaseni/apple/callback', [AuthController::class, 'appleCallback'], [GuestMiddleware::class]);
$router->post('/prihlaseni', [AuthController::class, 'login'], [GuestMiddleware::class]);
$router->post('/odhlaseni', [AuthController::class, 'logout'], [AuthMiddleware::class]);
$router->get('/odhlaseno', [AuthController::class, 'signedOut']);
$router->get('/zapomenute-heslo', [AuthController::class, 'showForgot'], [GuestMiddleware::class]);
$router->post('/zapomenute-heslo', [AuthController::class, 'forgot'], [GuestMiddleware::class]);
$router->get('/obnoveni-hesla', [AuthController::class, 'showReset'], [GuestMiddleware::class]);
$router->post('/obnoveni-hesla', [AuthController::class, 'reset'], [GuestMiddleware::class]);
$router->get('/overeni-emailu', [AuthController::class, 'verifyEmail']);
$router->get('/potvrzeni-emailu', [AuthController::class, 'confirmEmailChange']);

$router->get('/user', [DashboardController::class, 'index'], [AuthMiddleware::class]);
$router->post('/user/rezim', [DashboardController::class, 'setViewMode'], [AuthMiddleware::class]);
$router->get('/user/pritomnost', [DashboardController::class, 'presence'], [AuthMiddleware::class]);
$router->get('/user/stav-studia', [DashboardController::class, 'studioStatus'], [AuthMiddleware::class]);
$router->get('/user/overeni', [DashboardController::class, 'verifyNotice'], [AuthMiddleware::class]);
$router->post('/user/overeni', [DashboardController::class, 'resendVerification'], [AuthMiddleware::class]);
$router->get('/user/vstup', [DashboardController::class, 'access'], [AuthMiddleware::class]);
$router->post('/user/vstup', [DashboardController::class, 'openDoor'], [AuthMiddleware::class]);
$router->get('/user/moje-rezervace', [ReservationController::class, 'mine'], [AuthMiddleware::class]);
$router->get('/user/rezervace', [ReservationController::class, 'index'], [AuthMiddleware::class]);
$router->get('/user/rezervace/dostupnost', [ReservationController::class, 'availability'], [AuthMiddleware::class]);
$router->get('/user/rezervace/kalendar', [ReservationController::class, 'calendar'], [AuthMiddleware::class]);
$router->post('/user/rezervace', [ReservationController::class, 'store'], [AuthMiddleware::class]);
$router->get('/user/rezervace/platba', [ReservationController::class, 'paid'], [AuthMiddleware::class]);
$router->get('/user/rezervace/platba/zruseno', [ReservationController::class, 'checkoutCancel'], [AuthMiddleware::class]);
$router->post('/user/rezervace/{id}/zrusit', [ReservationController::class, 'cancel'], [AuthMiddleware::class]);
$router->get('/user/studio', [StudioController::class, 'index'], [AuthMiddleware::class, AdminMiddleware::class]);
$router->post('/user/studio', [StudioController::class, 'store'], [AuthMiddleware::class, AdminMiddleware::class]);
$router->post('/user/studio/ulozit', [StudioController::class, 'update'], [AuthMiddleware::class, AdminMiddleware::class]);
$router->get('/user/studio/ceny', [StudioController::class, 'prices'], [AuthMiddleware::class, AdminMiddleware::class]);
$router->post('/user/studio/ceny', [StudioController::class, 'savePrices'], [AuthMiddleware::class, AdminMiddleware::class]);
$router->get('/user/studio/doba', [StudioController::class, 'hoursPage'], [AuthMiddleware::class, AdminMiddleware::class]);
$router->post('/user/studio/doba', [StudioController::class, 'hours'], [AuthMiddleware::class, AdminMiddleware::class]);
$router->post('/user/studio/vyjimka', [StudioController::class, 'exception'], [AuthMiddleware::class, AdminMiddleware::class]);
$router->post('/user/studio/vyjimka/smazat', [StudioController::class, 'deleteException'], [AuthMiddleware::class, AdminMiddleware::class]);
$router->get('/user/platba/navrat', [PayController::class, 'returned'], [AuthMiddleware::class]);
$router->post('/user/platba/potvrdit', [PayController::class, 'confirm'], [AuthMiddleware::class]);
$router->get('/user/platba/{id}', [PayController::class, 'show'], [AuthMiddleware::class]);
$router->get('/user/clenstvi', [ProfileController::class, 'membership'], [AuthMiddleware::class]);
$router->post('/user/clenstvi', [ProfileController::class, 'buyMembership'], [AuthMiddleware::class]);
$router->get('/user/clenstvi/platba', [ProfileController::class, 'membershipPaid'], [AuthMiddleware::class]);
$router->get('/user/clenstvi/platba/zruseno', [ProfileController::class, 'membershipCheckoutCancel'], [AuthMiddleware::class]);
$router->get('/user/profil', [ProfileController::class, 'index'], [AuthMiddleware::class]);
$router->post('/user/profil', [ProfileController::class, 'update'], [AuthMiddleware::class]);
$router->post('/user/profil/heslo', [ProfileController::class, 'password'], [AuthMiddleware::class]);
$router->post('/user/profil/email', [ProfileController::class, 'email'], [AuthMiddleware::class]);
$router->post('/user/profil/avatar', [ProfileController::class, 'avatar'], [AuthMiddleware::class]);
$router->post('/user/profil/avatar/smazat', [ProfileController::class, 'deleteAvatar'], [AuthMiddleware::class]);
$router->post('/user/profil/relace/{id}/odhlasit', [ProfileController::class, 'revokeSession'], [AuthMiddleware::class]);
$router->post('/user/profil/odhlasit-vse', [ProfileController::class, 'logoutAll'], [AuthMiddleware::class]);
$router->post('/user/profil/oznameni', [ProfileController::class, 'notifications'], [AuthMiddleware::class]);
$router->get('/user/profil/export', [ProfileController::class, 'export'], [AuthMiddleware::class]);
$router->post('/user/profil/vymaz', [ProfileController::class, 'requestDeletion'], [AuthMiddleware::class]);
$router->get('/user/zabezpeceni/mfa', [ProfileController::class, 'showMfa'], [AuthMiddleware::class]);
$router->post('/user/zabezpeceni/mfa', [ProfileController::class, 'confirmMfa'], [AuthMiddleware::class]);
$router->post('/user/zabezpeceni/mfa/vypnout', [ProfileController::class, 'disableMfa'], [AuthMiddleware::class]);
$router->get('/user/zabezpeceni/mfa/qr', [ProfileController::class, 'mfaQr'], [AuthMiddleware::class]);
$router->get('/user/zabezpeceni/mfa/kody', [ProfileController::class, 'recoveryCodes'], [AuthMiddleware::class]);

$admin = [AuthMiddleware::class, AdminMiddleware::class];
$router->get('/user/sprava', [AdminController::class, 'dashboard'], $admin);
$router->get('/user/sprava/live', [AdminController::class, 'dashboardLive'], $admin);
$router->get('/user/sprava/trzby', [AdminController::class, 'revenue'], $admin);
$router->get('/user/sprava/statistiky', [AdminController::class, 'statistics'], $admin);
$router->get('/user/sprava/rezervace', [AdminController::class, 'reservations'], $admin);
$router->post('/user/sprava/rezervace/{id}/zrusit', [AdminController::class, 'cancelReservation'], $admin);
$router->get('/user/sprava/zakaznici', [AdminController::class, 'users'], $admin);
$router->get('/user/sprava/zakaznici/{id}', [AdminController::class, 'userShow'], $admin);
$router->post('/user/sprava/zakaznici/{id}', [AdminController::class, 'userUpdate'], $admin);
$router->post('/user/sprava/zakaznici/{id}/blokovat', [AdminController::class, 'userBlock'], $admin);
$router->post('/user/sprava/zakaznici/{id}/odblokovat', [AdminController::class, 'userUnblock'], $admin);
$router->post('/user/sprava/zakaznici/{id}/smazat', [AdminController::class, 'userDelete'], $admin);
$router->post('/user/sprava/zakaznici/{id}/role', [AdminController::class, 'userRole'], $admin);
$router->post('/user/sprava/zakaznici/{id}/clenstvi', [AdminController::class, 'assignMembership'], $admin);
$router->post('/user/sprava/zakaznici/{id}/clenstvi/odebrat', [AdminController::class, 'revokeMembership'], $admin);
$router->post('/user/sprava/zakaznici/{id}/clenstvi/reset', [AdminController::class, 'resetMembershipHistory'], $admin);
$router->get('/user/sprava/tarify', [AdminController::class, 'plans'], $admin);
$router->post('/user/sprava/tarify', [AdminController::class, 'savePlan'], $admin);
$router->get('/user/sprava/vstup', [AdminController::class, 'access'], $admin);
$router->get('/user/sprava/vstup/stav', [AdminController::class, 'doorLive'], $admin);
$router->post('/user/sprava/vstup/stav', [AdminController::class, 'setDoor'], $admin);
$router->get('/user/sprava/zajem', [AdminController::class, 'interest'], $admin);
$router->get('/user/sprava/zajem/export', [AdminController::class, 'exportInterest'], $admin);
$router->post('/user/sprava/zajem/{id}/smazat', [AdminController::class, 'deleteInterest'], $admin);
$router->get('/user/sprava/nastaveni', [AdminController::class, 'settings'], $admin);
$router->post('/user/sprava/nastaveni', [AdminController::class, 'saveSettings'], $admin);

// Kompatibilita starých /admin URL
$router->get('/admin', [AdminController::class, 'dashboard'], $admin);
$router->get('/admin/live', [AdminController::class, 'dashboardLive'], $admin);
$router->get('/admin/trzby', [AdminController::class, 'revenue'], $admin);
$router->get('/admin/statistiky', [AdminController::class, 'statistics'], $admin);
$router->get('/admin/rezervace', [AdminController::class, 'reservations'], $admin);
$router->post('/admin/rezervace/{id}/zrusit', [AdminController::class, 'cancelReservation'], $admin);
$router->get('/admin/zakaznici', [AdminController::class, 'users'], $admin);
$router->get('/admin/zakaznici/{id}', [AdminController::class, 'userShow'], $admin);
$router->post('/admin/zakaznici/{id}', [AdminController::class, 'userUpdate'], $admin);
$router->post('/admin/zakaznici/{id}/blokovat', [AdminController::class, 'userBlock'], $admin);
$router->post('/admin/zakaznici/{id}/odblokovat', [AdminController::class, 'userUnblock'], $admin);
$router->post('/admin/zakaznici/{id}/smazat', [AdminController::class, 'userDelete'], $admin);
$router->post('/admin/zakaznici/{id}/role', [AdminController::class, 'userRole'], $admin);
$router->post('/admin/zakaznici/{id}/clenstvi', [AdminController::class, 'assignMembership'], $admin);
$router->post('/admin/zakaznici/{id}/clenstvi/odebrat', [AdminController::class, 'revokeMembership'], $admin);
$router->post('/admin/zakaznici/{id}/clenstvi/reset', [AdminController::class, 'resetMembershipHistory'], $admin);
$router->get('/admin/clenstvi', [AdminController::class, 'plans'], $admin);
$router->post('/admin/clenstvi', [AdminController::class, 'savePlan'], $admin);
$router->get('/admin/vstup', [AdminController::class, 'access'], $admin);
$router->get('/admin/vstup/stav', [AdminController::class, 'doorLive'], $admin);
$router->post('/admin/vstup/stav', [AdminController::class, 'setDoor'], $admin);
$router->get('/admin/zajem', [AdminController::class, 'interest'], $admin);
$router->get('/admin/zajem/export', [AdminController::class, 'exportInterest'], $admin);
$router->post('/admin/zajem/{id}/smazat', [AdminController::class, 'deleteInterest'], $admin);
$router->get('/admin/nastaveni', [AdminController::class, 'settings'], $admin);
$router->post('/admin/nastaveni', [AdminController::class, 'saveSettings'], $admin);

$router->post('/platba/stripe', [StripeWebhookController::class, 'handle']);
